name: Compile with SourceMod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: ["1.10", "1.11"]

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
          echo ::set-env name=SOURCEMOD_PATH::$SOURCEMOD_PATH
          echo ::set-env name=SCRIPTS_PATH::$SOURCEMOD_PATH/scripting
      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}
          
      - name: Clone TTT
        uses: actions/checkout@v2
        with:
          repository: 'classywolves/private-ttt-mirror'
          ref: 'master'
          path: 'deps/ttt'
          
      - name: Setup TTT
        run: |
          TTT_INCLUDE=$GITHUB_WORKSPACE/deps/ttt/addons/sourcemod/scripting/include

      - name: Compile Plugins
        run: |
          for file in *.sp
          do
            echo -e "\nCompiling $file..."
            spcomp -E -w234 -O2 -v2 -i $SCRIPTS_PATH/include -i $TTT_INCLUDE $file
          done
        working-directory: 'store'
