name: Compile with SourceMod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: ["1.10", "1.11"]

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
          echo "SOURCEMOD_PATH=$SOURCEMOD_PATH" >> $GITHUB_ENV
          echo "SCRIPTS_PATH=$SOURCEMOD_PATH/scripting" >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Clone TTT
        uses: actions/checkout@v2
        with:
          repository: 'classywolves/private-ttt-mirror'
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: 'master'
          path: 'deps/ttt'

      - name: Setup TTT
        run: |
          TTT_PATH=$GITHUB_WORKSPACE/deps/ttt
          echo "TTT_INCLUDE=$TTT_PATH/addons/sourcemod/scripting/include" >> $GITHUB_ENV

      - name: Compile Plugins
        run: |
          for file in $(find . -type d \( -path ./include -o -path ./libs -o -path ./missions -o -path ./skills -o -name '*common.sp; \) -prune -false -o -name '*.sp')
          do
            echo -e "\nCompiling $file..."
            spcomp -E -w234 -O2 -v2 -i $TTT_INCLUDE -i $SCRIPTS_PATH/include $file
          done
        working-directory: ${{ env.SCRIPTS_PATH }}/
